### PR TITLE
Change to work with newer versions of Laravel and Bootstrap

### PR DESCRIPTION
**Pull request by Nirys**

### CODE REVIEW

**Comment by talvbansal** [comment]
@Nirys thanks for sending this PR, I had no idea people were still using this package!

I'll check it out asap and hopefully get this merged in quickly for you!

**Comment by Nirys** [comment]
Thanks @talvbansal - apologies, I think my linter doesn't line up with your linter's requirements.

Tested with my fresh Laravel install, and meets my needs, so I thought I'd use that rather than re-invent the wheel :)  Let me know if there's anything you'd like me to change.

**Comment by talvbansal** [comment]
Hey @Nirys im so sorry i only just got around to looking at this properly, everything looks great, the only thing i can see is that your final js and css files are not production builds (npm run prod / yarn prod).

I'm not sure if this is a big deal since we're recommending that we re-run them through webpack along with your other vue components anyway. 

Style CI should kick in for the code formatting so dont worry about that at all.

I'll wait for you to respond back to see if you have an opinion on this and we can merge the code in from there.

I guess we really need to look into moving this to bootstrap 4 or maybe even hold fire for a bit and go straight to 5!

**Comment by Nirys** [comment]
Hi @talvbansal, I've rerun the build for production, should be OK to merge?

**Comment by talvbansal** [comment]
Merged! Thanks again for taking the time to work on this I really do appreciate it @Nirys

**Pull request merged**
