### PR TITLE
Fix error display at RenameItemModal

### PR DESCRIPTION
**Pull request by jbruni**

### CODE REVIEW

**Comment by talvbansal** [comment]
Hi @jbruni, thanks for your PR, can you tell me whats broken that this fixes please?

I've checked and the errors for renaming a file and they're shown using the following component:

`https://github.com/talvbansal/media-manager/blob/master/resources/assets/js/components/Errors.vue`

The reason the item is added to an array is because the above errors component expects an array of one or more items for it to display.

Unless i'm missing something here?

**Comment by jbruni** [comment]
Doing `[error]` is wrapping an array inside an array, because `error` arrives as an array from server. When `Errors.vue` display it, the inner array (original `error`) is the first element of the outer/wrapper errors array.

The result is that the server error is displayed like this:

```
["This is the error message from server, with \"escape\" chars appearing."]
```

This PR makes such error to be displayed as:

```
This is the error message, with "escape" chars appearing.
```

**Comment by jbruni** [comment]
At `CreateFolderModal` you got it right:

https://github.com/talvbansal/media-manager/blob/master/resources/assets/js/components/CreateFolderModal.vue#L91-L93

**Comment by talvbansal** [comment]
@jbruni thanks for the replying! I'll merge this in asap! :)

**Pull request merged**
